#spring.datasource.url=jdbc:sqlserver://aquatracker-server-rk.database.windows.net:1433;database=aquatracker-server-rk;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;

#spring.datasource.username=robertkuzba

#spring.datasource.password=Aquatracker1234

#spring.jpa.hibernate.ddl-auto=update

#spring.jpa.show-sql=true

# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

spring.profiles.active=dev