name: Run API Smoke Tests

on:   
  push:   
    branches: [ master ] 
  pull_request: 
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest   

    services:
      postgres:               
        image: postgres:17
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Pobierz kod
      uses: actions/checkout@v4

    - name: Zainstaluj Java
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Uruchom backend w tle
      run: |
        nohup ./mvnw spring-boot:run -Dspring-boot.run.arguments="--spring.datasource.url=jdbc:postgresql://localhost:5432/postgres --spring.datasource.username=postgres --spring.datasource.password=postgres" &
        echo "Czekam 40 sekund na start backendu..."
        sleep 40

    - name: Zainstaluj Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Uruchom testy API (Smoke Tests)
      continue-on-error: true
      env:
        COGNITO_CLIENT_ID: ${{ secrets.COGNITO_CLIENT_ID }}
        TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
        TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
        TEST_USER_ID: ${{ secrets.TEST_USER_ID }}
        AWS_REGION: "eu-north-1"
        JWT: ${{ secrets.JWT_TOKEN }}   
      run: |
        cd tests/Api
        node api-test.js